/*
 * This source file was generated by the Gradle 'init' task
 */
package br.org.precatoriosleak.app;

import br.org.precatoriosleak.list.LinkedList;

import static br.org.precatoriosleak.utilities.StringUtils.join;
import static br.org.precatoriosleak.utilities.StringUtils.split;
import static br.org.precatoriosleak.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
