/*
 * This source file was generated by the Gradle 'init' task
 */
package br.org.precatoriosleak.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
