/*
 * This source file was generated by the Gradle 'init' task
 */
package br.org.precatoriosleak.utilities;

import br.org.precatoriosleak.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
