name: Deploy Azure Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'infra/terraform/**' ]

env:
  TF_VERSION: 1.5.5
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
      
      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init
      
      - name: Terraform Plan
        working-directory: ./infra/terraform
        run: terraform plan -var "location=brazilsouth"
      
      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve -var "location=brazilsouth"
