name: Deploy Azure Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'infra/terraform/**' ]

env:
  TF_VERSION: 1.12.0
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/terraform
        run: |
          terraform plan \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            -var "client_id=${{ secrets.AZURE_CLIENT_ID }}"
            -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: |
          terraform apply -auto-approve \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            -var "client_id=${{ secrets.AZURE_CLIENT_ID }}"
            -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
